import { PermissionRow } from '../../models/permission.model';

export const MOCK_PERMISSIONS: PermissionRow[] = [
    {
        function: 'Cấu hình hệ thống',
        create: true,
        view: true,
        update: true,
        delete: false,
        approve: false,
        approver: false,
        crudTask: false,
    },
    {
        function: 'Quản lý danh mục',
        create: true,
        view: true,
        update: true,
        delete: true,
        approve: false,
        approver: false,
        crudTask: false,
    },
    {
        function: 'Quản lý người dùng',
        create: true,
        view: true,
        update: true,
        delete: true,
        approve: true,
        approver: true,
        crudTask: false,
    },
    {
        function: 'Quản lý phiếu yêu cầu',
        create: true,
        view: true,
        update: true,
        delete: false,
        approve: true,
        approver: false,
        crudTask: true,
    },
    {
        function: 'Quản lý chấm công',
        create: false,
        view: true,
        update: false,
        delete: false,
        approve: true,
        approver: false,
        crudTask: false,
    },
    {
        function: 'Quản lý dự án',
        create: true,
        view: true,
        update: true,
        delete: false,
        approve: false,
        approver: false,
        crudTask: true,
    },
    {
        function: 'Đánh giá',
        create: true,
        view: true,
        update: true,
        delete: false,
        approve: false,
        approver: false,
        crudTask: false,
    },
    {
        function: 'Tin tức',
        create: true,
        view: true,
        update: true,
        delete: true,
        approve: false,
        approver: false,
        crudTask: false,
    },
    {
        function: 'Lộ trình học tập',
        create: true,
        view: true,
        update: true,
        delete: false,
        approve: false,
        approver: false,
        crudTask: false,
    },
    {
        function: 'Hòm thư góp ý',
        create: false,
        view: true,
        update: false,
        delete: false,
        approve: true,
        approver: false,
        crudTask: false,
    },
];
